local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
    s("report", {
        t({
            "\\documentclass[a4paper,12pt]{report}",
            "",
            "\\usepackage{luatexja}",
            "\\usepackage{luatexja-fontspec}",
            "\\setmainjfont[BoldFont={HaranoAjiMincho-Bold}]{HaranoAjiMincho-Regular}",
            "\\setsansjfont[BoldFont={HaranoAjiGothic-Bold}]{HaranoAjiGothic-Medium}",
            "",
            "\\usepackage{pdfpages}",
            "\\usepackage{siunitx}",
            "\\usepackage{enumitem}",
            "\\usepackage{titlesec}",
            "\\usepackage{graphicx}",
            "\\usepackage{caption}",
            "\\usepackage{amsmath}",
            "\\usepackage{ulem}",
            "\\usepackage{listings}",
            "\\usepackage[dvipsnames]{xcolor}",
            "\\usepackage{hyperref}",
            "\\usepackage[framemethod=TikZ]{mdframed}",
            "\\usepackage{lmodern}",
            "\\usepackage{pifont}",
            "\\usepackage{varwidth}",
            "\\usepackage{url}",
            "",
            "\\captionsetup[figure]{name=図}",
            "",
            "\\definecolor{codebg}{RGB}{245,245,245}",
            "\\definecolor{identifiercolor}{RGB}{7,54,66}",
            "\\definecolor{commentcolor}{RGB}{88,110,117}",
            "\\definecolor{linenumbercolor}{RGB}{0,0,0}",
            "\\definecolor{framecolor}{RGB}{200,200,200}",
            "\\definecolor{keywordcolor}{RGB}{38,139,210}",
            "\\definecolor{builtincolor}{RGB}{133,153,0}",
            "\\definecolor{stringcolor}{RGB}{42,161,152}",
            "\\definecolor{numbercolor}{RGB}{203,75,22}",
            "",
            "\\lstdefinestyle{codestyle}{",
            "  backgroundcolor=\\color{codebg},",
            "  basicstyle=\\linespread{1.1}\\small\\ttfamily\\color{identifiercolor},",
            "  frame=single,",
            "  framerule=0.5pt,",
            "  rulecolor=\\color{framecolor},",
            "  breaklines=true,",
            "  showstringspaces=false,",
            "  numbers=left,",
            "  xleftmargin=2em,",
            "  keywordstyle=\\color{keywordcolor}\\bfseries,",
            "  stringstyle=\\color{stringcolor},",
            "  commentstyle=\\color{commentcolor}\\itshape,",
            "  numberstyle=\\color{numbercolor},",
            "}",
            "",
            "\\lstdefinestyle{python}{",
            "  style=codestyle,",
            "  language=Python,",
            "  morekeywords=[2]{self,True,False,None,print,range,len,dict,list,set,zip,int,str,float,max,min,hasattr,open,round,list,tuple,set,dict,Exception,ValueError,FileNotFoundError,StopIteration,__name__},",
            "  keywordstyle=[2]\\color{builtincolor},",
            "}",
            "",
            "\\lstdefinestyle{c}{",
            "  style=codestyle,",
            "  language=C,",
            "  morekeywords=[2]{printf,fprintf,fopen,fclose,malloc,free,exit,srand,rand,FILE,NULL,stderr,bool,true,false,long long},",
            "  keywordstyle=[2]\\color{builtincolor},",
            "}",
            "",
            "\\lstset{",
            "  style=python,",
            "  numberstyle=\\tiny\\color{linenumbercolor}",
            "}",
            "",
            "\\colorlet{LightGreen}{Green!20}",
            "\\colorlet{LightBlue}{Cyan!20}",
            "\\newmdenv[",
            "  linecolor=black,",
            "  linewidth=1pt,",
            "  roundcorner=5pt,",
            "  backgroundcolor=LightGreen,",
            "  innertopmargin=10pt,",
            "  innerbottommargin=10pt,",
            "  innerleftmargin=10pt,",
            "  innerrightmargin=10pt,",
            "  skipabove=\\topsep,",
            "  skipbelow=\\topsep,",
            "]{specbox}",
            "",
            "\\usepackage[top=25mm,bottom=25mm,left=25mm,right=25mm]{geometry}",
            "",
            "\\captionsetup{compatibility=false}",
            "\\captionsetup{labelsep=colon}",
            "",
            "\\renewcommand{\\thesection}{\\arabic{section}}",
            "",
            "\\titleformat{\\section}",
            "  {\\normalfont\\fontsize{14pt}{16pt}\\selectfont\\bfseries}",
            "  {\\thesection.}{1em}{}",
            "",
            "\\titleformat{\\subsection}",
            "  {\\normalfont\\fontsize{13pt}{14pt}\\selectfont\\bfseries}",
            "  {\\thesubsection. }{1em}{}",
            "",
            "\\titleformat{\\subsubsection}",
            "  {\\normalsize\\bfseries}",
            "  {\\thesubsubsection.}{1em}{}",
            "",
            "\\titleformat{\\paragraph}",
            "  {\\normalsize\\bfseries}",
            "  {}{0em}{}",
            "",
            "\\titleformat{\\subparagraph}",
            "  {\\normalsize\\bfseries}",
            "  {}{0em}{}",
            "",
            "\\titlespacing*{\\subparagraph}{0pt}{2ex}{1ex}",
            "",
            "\\hypersetup{",
            "  colorlinks=true,",
            "  linkcolor=black,",
            "  urlcolor=black,",
            "}",
            "",
            "\\usepackage{fontspec}",
            "\\setmainfont{Times New Roman}",
            "\\setsansfont{Arial}",
            "\\newfontfamily\\sectionfont{Times New Roman}",
            "\\titleformat{\\section}",
            "  {\\sectionfont\\fontsize{14pt}{16pt}\\selectfont\\bfseries}",
            "  {\\thesection.}{1em}{}",
            "\\titleformat{\\subsection}",
            "  {\\sectionfont\\fontsize{13pt}{14pt}\\selectfont\\bfseries}",
            "  {\\thesubsection.}{1em}{}",
            "",
            "\\begin{document}",
            "",
            "\\title{",
        }),
        i(1, "タイトル"),
        t({ "}", "\\author{中山 将吾}", "\\date{\\today}", "\\maketitle", "" }),
        t("\\section{"),
        i(2, "セクション名"),
        t({ "}", "", "" }),
        i(0),
        t({ "", "\\end{document}" }),
    }),
}
