local ls = require("luasnip")
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node
local f = ls.function_node

return {
    s("report", {
        t({
            "\\documentclass[a4paper,12pt]{ltjsreport}",
            "",
            "\\usepackage{luatexja}",
            "\\usepackage{luatexja-fontspec}",
            "\\setcounter{secnumdepth}{3}",
            "",
            "\\setmainfont{Times New Roman}",
            "\\setsansfont{Arial}",
            "\\setmainjfont[BoldFont=Harano Aji Mincho Bold]{Harano Aji Mincho}",
            "",
            "\\usepackage{pdfpages}",
            "\\usepackage{siunitx}",
            "\\usepackage{enumitem}",
            "\\usepackage{titlesec}",
            "\\usepackage{graphicx}",
            "\\usepackage{caption}",
            "\\usepackage{amsmath}",
            "\\usepackage{ulem}",
            "\\usepackage{listings}",
            "\\usepackage[dvipsnames]{xcolor}",
            "\\usepackage{hyperref}",
            "\\usepackage[framemethod=TikZ]{mdframed}",
            "\\usepackage{pifont}",
            "\\usepackage{varwidth}",
            "\\usepackage{url}",
            "\\usepackage{here}",
            "\\usepackage{makecell}",
            "\\usepackage{hhline}",
            "\\usepackage{tabularray}",
            "\\usepackage{diagbox}",
            "\\usepackage{tikz}",
            "",
            "\\captionsetup[figure]{name=図}",
            "\\captionsetup{compatibility=false}",
            "\\captionsetup{labelsep=colon}",
            "",
            "\\usepackage[top=20mm,bottom=20mm,left=20mm,right=20mm]{geometry}",
            "",
            "\\definecolor{codebg}{RGB}{245,245,245}",
            "\\definecolor{identifiercolor}{RGB}{7,54,66}",
            "\\definecolor{commentcolor}{RGB}{88,110,117}",
            "\\definecolor{linenumbercolor}{RGB}{0,0,0}",
            "\\definecolor{framecolor}{RGB}{200,200,200}",
            "\\definecolor{keywordcolor}{RGB}{38,139,210}",
            "\\definecolor{builtincolor}{RGB}{133,153,0}",
            "\\definecolor{stringcolor}{RGB}{42,161,152}",
            "\\definecolor{numbercolor}{RGB}{203,75,22}",
            "",
            "\\lstdefinestyle{codestyle}{",
            "  backgroundcolor=\\color{codebg},",
            "  basicstyle=\\linespread{1.1}\\small\\ttfamily\\color{identifiercolor},",
            "  frame=single,",
            "  framerule=0.5pt,",
            "  rulecolor=\\color{framecolor},",
            "  breaklines=true,",
            "  showstringspaces=false,",
            "  numbers=left,",
            "  xleftmargin=2em,",
            "  keywordstyle=\\color{keywordcolor}\\bfseries,",
            "  stringstyle=\\color{stringcolor},",
            "  commentstyle=\\color{commentcolor}\\itshape,",
            "  numberstyle=\\normalsize\\color{black},",
            "}",
            "",
            "\\lstdefinestyle{python}{",
            "  style=codestyle,",
            "  language=Python,",
            "  morekeywords=[2]{self,True,False,None,print,range,len,dict,list,set,zip,int,str,float,max,min,open,round,tuple,Exception,ValueError,FileNotFoundError,__name__},",
            "  keywordstyle=[2]\\color{builtincolor},",
            "}",
            "",
            "\\lstdefinestyle{cpp}{",
            "  style=codestyle,",
            "  language=C++,",
            "  morekeywords=[2]{",
            "    nullptr,bool,true,false,",
            "    uint8_t,uint16_t,uint32_t,",
            "    int8_t,int16_t,int32_t,",
            "    size_t,String,",
            "    setup,loop,",
            "    pinMode,digitalWrite,digitalRead,",
            "    analogRead,analogWrite,",
            "    delay,delayMicroseconds,",
            "    millis,micros,",
            "    HIGH,LOW,INPUT,OUTPUT,INPUT_PULLUP,",
            "    Serial,begin,print,println,write,available,read,",
            "    SoftwareSerial",
            "  },",
            "  keywordstyle=[2]\\color{builtincolor},",
            "}",
            "",
            "\\lstset{",
            "  style=python",
            "}",
            "",
            "\\hypersetup{",
            "  colorlinks=true,",
            "  linkcolor=black,",
            "  urlcolor=black,",
            "  citecolor=black",
            "}",
            "",
            "% ----------------------------------------------------------------",
            "% \\chapterなしで\\sectionを1. 2. 3. ...にするための設定",
            "% \\chapter を使わず、\\sectionを1. から始めたい場合に、",
            "% 次の4行のコメントアウト（%）を外してください。",
            "%\\makeatletter",
            "%\\@removefromreset{section}{chapter}",
            "%\\makeatother",
            "%\\renewcommand{\\thesection}{\\arabic{section}}",
            "% ----------------------------------------------------------------",
            "",
            "\\titleclass{\\chapter}{straight}",
            "\\titleformat{\\chapter}[block]",
            "  {\\fontsize{16pt}{18pt}\\selectfont\\bfseries}",
            "  {第\\thechapter 章\\quad}",
            "  {0pt}",
            "  {}",
            "\\titlespacing*{\\chapter}{0pt}{20pt}{15pt}",
            "",
            "\\titleformat{\\section}",
            "  {\\fontsize{14pt}{16pt}\\selectfont\\bfseries}",
            "  {\\thesection\\quad}",
            "  {0pt}",
            "  {}",
            "\\titlespacing*{\\section}{0pt}{15pt}{10pt}",
            "",
            "\\titleformat{\\subsection}",
            "  {\\fontsize{12pt}{14pt}\\selectfont\\bfseries}",
            "  {\\thesubsection\\quad}",
            "  {0pt}",
            "  {}",
            "\\titlespacing*{\\subsection}{0pt}{10pt}{5pt}",
            "",
            "\\titleformat{\\subsubsection}",
            "  {\\normalsize\\bfseries}",
            "  {\\thesubsubsection\\quad}",
            "  {0pt}",
            "  {}",
            "",
            "\\usepackage[",
            "  backend=biber,",
            "  style=numeric,",
            "  sorting=none,",
            "  bibencoding=utf8",
            "]{biblatex}",
            "\\addbibresource{ref/references.bib}",
            "\\DeclareFieldFormat*{title}{#1}",
            "\\DeclareFieldFormat*{journaltitle}{#1}",
            "\\DeclareFieldFormat*{booktitle}{#1}",
            "\\DeclareFieldFormat{url}{\\url{#1}}",
            "\\DefineBibliographyStrings{english}{",
            "  urlseen = {参照},",
            "}",
            "\\DeclareFieldFormat{title}{#1}",
            "\\DeclareFieldFormat{booktitle}{#1}",
            "\\ExecuteBibliographyOptions{",
            "  date=ymd,",
            "  urldate=ymd,",
            "  seconds=false",
            "}",
            "",
            "\\usepackage{indentfirst}",
            "\\sisetup{",
            "  detect-all,",
            "  mode=math",
            "}",
            "",
            "\\begin{document}",
            "",
            "%\\includepdf{./cover.pdf}",
            "",
            "% ===== 目次 =====",
            "%\\tableofcontents",
            "%\\thispagestyle{empty}",
            "%\\clearpage",
            "",
            "\\setcounter{page}{1}",
            "",
            "\\begin{titlepage}",
            "  \\vspace*{\\stretch{1.0}}",
            "",
            "  \\begin{flushright}",
            "    \\large{提出日：",
        }),
        f(function()
            return os.date("%Y年%m月%d日")
        end),
        t({
            "}",
            "  \\end{flushright}",
            "",
            "  \\vspace*{\\stretch{2.3}}",
            "",
            "  \\begin{center}",
            "    {\\huge 授業名：アルゴリズムとデータ構造} \\\\",
            "    {\\vspace{1cm}}",
            "    {\\huge No.",
        }),
        i(1),
        t({
            "}",
            "  \\end{center}",
            "",
            "  \\vspace*{\\stretch{3.0}}",
            "",
            "  \\begin{center}",
            "    {\\large 所属：電子情報工学科3年} \\\\",
            "    \\vspace{0.5cm}",
            "    {\\large 学籍番号：i231331}\\\\",
            "    \\vspace{0.5cm}",
            "    {\\large 氏名：中山 将吾}",
            "  \\end{center}",
            "",
            "  \\vspace*{\\stretch{1.0}}",
            "\\end{titlepage}",
            "",
            "\\chapter{",
        }),
        i(2, "実験タイトル"),
        t({
            "}",
            "",
            "\\section{目的}",
            "",
        }),
        i(3),
        t({
            "",
            "\\section{原理}",
            "",
            "\\section{使用機器}",
            "",
            "\\section{実験方法}",
            "",
            "\\section{結果}",
            "",
            "\\section{考察}",
            "",
            "\\section{結論}",
            "",
            "\\section{参考文献}",
            "",
        }),
        i(0),
        t({
            "",
            "\\printbibliography",
            "",
            "\\end{document}",
        }),
    }),

    s("chapter", {
        t("\\chapter{"),
        i(1, "実験タイトル"),
        t({
            "}",
            "",
            "\\section{目的}",
            "",
        }),
        i(2),
        t({
            "",
            "\\section{原理}",
            "",
            "\\section{使用機器}",
            "",
            "\\section{実験方法}",
            "",
            "\\section{結果}",
            "",
            "\\section{考察}",
            "",
            "\\section{結論}",
            "",
            "\\section{参考文献}",
            "",
        }),
        i(0),
    }),
}
